Repository brmodeloweb/brmodelo-app, pull requests merged in 2020-06, with the labels that each got.

#96 Update gulpfile.js to Gulp4 syntax
  .gitignore
  app/.DS_Store
  app/angular/service/conceptualFactory.js
  app/angular/view/conceptual.html
  app/angular/view/logic.html
  app/angular/view/login.html
  app/angular/view/mainHeader.html
  app/angular/view/register.html
  app/img/120_01.png
  app/img/120_02.png
  app/img/120_55.png
  app/img/atributo_composto.png
  app/img/brlogo.png
  app/img/composto-01.png
  app/img/favicon.ico
  app/img/loading-dots.gif
  app/img/logo.eps
  app/img/logo_2.png
  app/img/logo_test.png
  app/img/logo_test_2.png
  app/img/logotest120.png
  app/imgs/.DS_Store
  app/joint/jquery.min.js
  app/joint/jquery.min.map
  app/sass/app.scss
  app/sass/mainHeader.scss
  app/sass/structure.scss
  gulpfile.js
  package-lock.json
  package.json
  server.js
  server_app/.DS_Store
  views/index.html
Labels: frontend

#108 Update dependencies: del, ejs
  package.json
Labels: Dependencies

#109 Add .editorconfig
  .editorconfig
  app/angular/app.js
  app/angular/controller/mainController.js
  app/angular/controller/modal/sqlGeneratorModalController.js
  app/angular/controller/models/conceptualController.js
  app/angular/controller/models/logicController.js
  app/angular/directive/br-option.js
  app/angular/directive/br-select-dropdown.html
  app/angular/directive/br-select-dropdown.js
  app/angular/directive/br-select-option.js
  app/angular/directive/br-selectOption.js
  app/angular/service/logicFactory.js
  app/angular/service/sqlGeneratorService.js
  gulpfile.js
  server.js
  server_app/helpers/hash.js
  server_app/models/model.js
Labels: Development

#93 Setup eslint (#91)
  .eslintrc
  .gitignore
  package.json
Labels: Development
