Repository brmodeloweb/brmodelo-app, pull requests merged in 2021-11, with the labels that each got.

#250 Fix JointJS style in the logic model
  app/angular/conceptual/conceptual.js
  app/angular/index.js
Labels: Bug

#248 Register keyboard shortcuts
  app/angular/components/keyboardController.js
  app/angular/conceptual/conceptual.html
  app/angular/conceptual/conceptual.js
  app/angular/logic/logic.html
  app/angular/logic/logic.js
  app/angular/service/logicService.js
  app/angular/service/modelAPI.js
  app/angular/workspace/workspace.js
  app/joint/br-scroller.js
  package.json
  yarn.lock
Labels: Frontend, Feature request, Improvement

#252 Add date fields to model database
  server_app/model/model.js
  server_app/model/service.js
  server_app/user/model.js
Labels: Backend

#254 Refactor existing tests and add new ones
  cypress.json
  cypress/integration/login.spec.js
  cypress/integration/models.spec.js
  cypress/support/commands.js
Labels: Test coverage

#257 167 - Prevent exit without saving
  .babelrc
  app/angular/components/confirmationModal.html
  app/angular/components/confirmationModal.js
  app/angular/conceptual/conceptual.js
  app/angular/logic/logic.js
  app/angular/service/logicService.js
  app/angular/service/preventExitService.js
  package.json
  webpack.config.js
  yarn.lock
Labels: Feature, Improvement

#260 Increase test coverage
  cypress.json
  cypress/integration/models.spec.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: Test coverage

#259 Adjust zoom keyboard shortcut
  app/angular/components/keyboardController.js
  app/angular/conceptual/conceptual.html
  app/angular/conceptual/conceptual.js
  app/angular/logic/logic.html
  app/angular/logic/logic.js
  app/angular/service/logicService.js
  app/joint/br-scroller.js
Labels: Improvement

#264 Improve entities connection #229
  app/angular/conceptual/conceptual.js
  app/angular/conceptual/linker.js
  app/angular/conceptual/sidebarControl.js
  app/angular/service/logicService.js
  app/angular/service/toolsViewService.js
  app/joint/shapes.js
  app/sass/joint-custom.scss
Labels: Feature request, Improvement

#262 Upgrade node to v16
  .gitignore
  .nvmrc
  Dockerfile
  package.json
  yarn.lock
Labels: Infra

#263 Internacionalization support (English and Portuguese)
  app/angular/components/conversionOptionModal.html
  app/angular/components/createModelModal.html
  app/angular/components/createModelModal.js
  app/angular/components/deleteModelModal.html
  app/angular/components/duplicateModelModal.html
  app/angular/components/duplicateModelModal.js
  app/angular/components/renameModelModal.html
  app/angular/components/sqlGeneratorModal.html
  app/angular/conceptual/conceptual.html
  app/angular/conceptual/conceptual.js
  app/angular/conceptual/sidebarControl.html
  app/angular/index.js
  app/angular/logic/logic.html
  app/angular/logic/logic.js
  app/angular/login/login.html
  app/angular/login/login.js
  app/angular/recovery/recovery.html
  app/angular/recovery/recovery.js
  app/angular/recovery/reset.html
  app/angular/recovery/reset.js
  app/angular/service/conversorService.js
  app/angular/signup/signup.html
  app/angular/signup/signup.js
  app/angular/workspace/workspace.html
  app/angular/workspace/workspace.js
  app/i18n/languages/en.js
  app/i18n/languages/pt_BR.js
  cypress/integration/login.spec.js
  cypress/integration/models.spec.js
  cypress/support/commands.js
Labels: Frontend, Improvement

#273 Fix list display after duplicate model action
  app/angular/workspace/workspace.js
Labels: Bug

#249 Add constraints to logical and physical design
  app/angular/logic/logic.html
  app/angular/logic/logic.js
  app/angular/service/Column.js
  app/angular/service/conversorService.js
  app/angular/service/logicService.js
  app/angular/service/sqlGeneratorService.js
  app/sass/form.scss
Labels: Improvement

#267 Refactor tests and increase coverage
  app/angular/logic/logic.js
  app/angular/service/preventExitService.js
  app/angular/workspace/workspace.js
  app/i18n/languages/en.js
  app/i18n/languages/pt_BR.js
  cypress/integration/login.spec.js
  cypress/integration/model.spec.js
  cypress/integration/models.spec.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: Test coverage
