Repository brmodeloweb/brmodelo-app, pull requests merged in 2021-12, with the labels that each got.

#275 Update README.md
  README.md
Labels: Documentation

#286 Upgrade cypress to v9.1.1
  package.json
  yarn.lock
Labels: Test coverage

#288 Add EditoConfig to list of applications you will need to run the app
  README.md
Labels: Development

#293 Update project dependencies
  .gitignore
  README.md
  app/angular/login/login.html
  app/img/logo.eps
  package.json
  server_app/app.js
  server_app/model/service.js
  server_app/user/service.js
  webpack.config.js
  yarn.lock
Labels: Development, Frontend, Backend, Infra

#295 Add column only if has target table (fix cypress test and console error)
  app/angular/service/logicService.js
Labels: Bug

#302 Login page: Change language selector styles
  app/angular/login/login.html
  app/i18n/languages/en.js
  app/i18n/languages/pt_BR.js
  app/img/br-flag.svg
  app/img/us-flag.svg
  app/sass/public.scss
  cypress/integration/login.spec.js
Labels: Translations

#303 Refactor Cypress tests authentication
  cypress.json
  cypress/integration/api/model.spec.js
  cypress/integration/login.spec.js
  cypress/integration/model.spec.js
  cypress/integration/models.spec.js
  cypress/support/commands.d.ts
  cypress/support/commands.js
Labels: Test coverage, Documentation

#289 Adds Typescript support to React
  .eslintrc
  app/react/.eslintrc
  app/react/.prettierrc
  app/react/components/Button/Button.jsx
  app/react/components/Button/Button.tsx
  app/react/components/Button/index.ts
  app/react/containers/Providers/Providers.tsx
  app/react/containers/Providers/index.ts
  app/react/theme/index.ts
  app/react/tsconfig.json
  package.json
  webpack.config.js
  yarn.lock
Labels: Frontend, Improvement

#266 Show last saved date
  app/angular/components/bugReportButton/index.js
  app/angular/components/bugReportButton/template.html
  app/angular/components/statusBar/index.js
  app/angular/components/statusBar/styles.scss
  app/angular/components/statusBar/template.html
  app/angular/conceptual/conceptual.html
  app/angular/conceptual/conceptual.js
  app/angular/logic/logic.html
  app/angular/logic/logic.js
  app/angular/login/login.html
  app/angular/login/login.js
  app/angular/recovery/recovery.html
  app/angular/recovery/recovery.js
  app/angular/recovery/reset.html
  app/angular/recovery/reset.js
  app/angular/service/logicService.js
  app/angular/signup/signup.html
  app/angular/signup/signup.js
  app/angular/workspace/workspace.html
  app/angular/workspace/workspace.js
  app/i18n/languages/en.js
  app/i18n/languages/pt_BR.js
  app/sass/buttons.scss
  app/sass/structure.scss
Labels: Improvement

#298 User menu improvements
  app/angular/components/dropdown.html
  app/angular/components/dropdownIcon.html
  app/i18n/languages/en.js
  app/i18n/languages/pt_BR.js
Labels: Improvement

#255 feature: import model endpoint
  .env.example
  package.json
  server_app/app.js
  server_app/middleware/middleware.js
  server_app/model/handler.js
  server_app/model/handler.test.js
  server_app/model/test_files/test.brm
Labels: Feature, API

#290 Adds i18Next support to React
  app/react/containers/Providers/Providers.tsx
  app/react/i18n/index.ts
  app/react/public/locales/en/common.json
  app/react/public/locales/en/login.json
  app/react/public/locales/pt-BR/common.json
  app/react/public/locales/pt-BR/login.json
  app/react/tsconfig.json
  app/react/utils/enums/localeNamespaces.ts
  package.json
  webpack.config.js
  yarn.lock
Labels: Frontend, Improvement

#308 Add link to documentation page
  app/angular/components/dropdownIcon.html
Labels: Improvement

#309 Remove devDependency added by mistake
  package.json
  yarn.lock
Labels: Dependencies
